remove yandex auth
cybergizer-hq/alfred pull request #4
Opened 2022-08-29 18:12 UTC by yournumberone

2022-08-30 08:14 UTC, Vadser submitted a review, later dismissed

2022-09-01 07:08 UTC, anatoliliotych requested changes

2022-09-01 07:08 UTC, anatoliliotych commented on app/controllers/users/omniauth_callbacks_controller.rb
> +      return if response.any? { |h| h['id'] == CYBERGIZER_ID }
can we redo this and make this project cybergizer agnostic?

2022-09-01 07:08 UTC, anatoliliotych commented on app/controllers/users/omniauth_callbacks_controller.rb
> +    CYBERGIZER_ID = '814747458839511071'
gosh! env variables

2022-09-01 07:08 UTC, anatoliliotych commented on app/controllers/users/omniauth_callbacks_controller.rb
> +    def filter_cg_members
naming should be better

2023-02-16 12:05 UTC, closed without merging